idf_component_register(
    SRCS
        "main.c"
        "sht40.c"
        "bmp280.c"
        "mpu9250.c"
        "ssd1315.c"
        "ekf_ahrs.c"
        "imu_filter.c"
        "imu_bias_calib.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        esp_driver_i2c
        esp_driver_gpio
        esp_timer
        esp_system
        freertos
)
